DROP TABLE IF EXISTS pokemon;

create table pokemon(
	numero INT AUTO_INCREMENT PRIMARY KEY,
    nome varchar(20) not null,
    descricao varchar(150) not null,
    tipo1 varchar(12) not null,
    tipo2 varchar(12)
);

INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (1, 'Bulbasaur', 'BULBASAUR', 'Grama', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (2, 'Ivysaur', 'IVYSAUR', 'Grama', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (3, 'Venusaur', 'VENUSAUR', 'Grama', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (4, 'Charmander', 'CHARMANDER', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (5, 'Charmeleon', 'CHARMELEON', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (6, 'Charizard', 'CHARIZARD', 'Fogo', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (7, 'Squirtle', 'SQUIRTLE', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (8, 'Wartortle', 'WARTORTLE', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (9, 'Blastoise', 'BLASTOISE', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (10, 'Caterpie', 'CATERPIE', 'Inseto', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (11, 'Metapod', 'METAPOD', 'Inseto', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (12, 'Butterfree', 'BUTTERFREE', 'Inseto', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (13, 'Weedle', 'WEEDLE', 'Inseto', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (14, 'Kakuna', 'KAKUNA', 'Inseto', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (15, 'Beedrill', 'BEEDRILL', 'Inseto', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (16, 'Pidgey', 'PIDGEY', 'Voador', 'Normal');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (17, 'Pidgeotto', 'PIDGEOTTO', 'Voador', 'Normal');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (18, 'Pidgeot', 'PIDGEOT', 'Voador', 'Normal');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (19, 'Rattata', 'RATTATA', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (20, 'Raticate', 'RATICATE', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (21, 'Spearow', 'SPEAROW', 'Voador', 'Normal');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (22, 'Fearow', 'FEAROW', 'Voador', 'Normal');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (23, 'Ekans', 'EKANS','Venenoso', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (24, 'Arbok', 'ARBOK','Venenoso', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (25, 'Pikachu', 'PIKACHU','Elétrico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (26, 'Raichu', 'RAICHU','Elétrico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (27, 'Sandshrew', 'SANDSHREW','Terra', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (28, 'Sandslash', 'SANDSLASH','Terra', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (29, 'Nidoran ♀', 'NIDORANF','Venenoso', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (30, 'Nidorina', 'NIDORINA','Venenoso', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (31, 'Nidoqueen', 'NIDOQUEEN','Venenoso', 'Terra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (32, 'Nidoran ♂', 'NIDORANM','Venenoso', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (33, 'Nidorino', 'NIDORINO','Venenoso', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (34, 'Nidoking', 'NIDOKING','Venenoso', 'Terra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (35, 'Clefairy', 'CLEFAIRY','Fada', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (36, 'Clefable', 'CLEFABLE','Fada', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (37, 'Vulpix', 'VULPIX', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (38, 'Ninetales', 'NINETALES', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (39, 'Jigglypuff', 'JIGGLYPUFF', 'Normal', 'Fada');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (40, 'Wigglytuff', 'WIGGLYTUFF', 'Normal', 'Fada');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (41, 'Zubat', 'ZUBAT', 'Venenoso', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (42, 'Golbat', 'GOLBAT', 'Venenoso', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (43, 'Oddish', 'ODDISH', 'Grama', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (44, 'Gloom', 'GLOOM', 'Grama', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (45, 'Vileplume', 'VILEPLUME', 'Grama', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (46, 'Paras', 'Inseto', 'PARAS', 'Grama');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (47, 'Parasect', 'PARASECT', 'Inseto', 'Grama');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (48, 'Venonat', 'VENONAT', 'Inseto', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (49, 'Venomoth', 'VENOMOTH', 'Inseto', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (50, 'Diglett', 'DIGLETT', 'Terra', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (51, 'Dugtrio', 'DUGTRIO', 'Terra', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (52, 'Meowth', 'MEOWTH', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (53, 'Persian', 'PERSIAN', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (54, 'Psyduck', 'PSYDUCK', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (55, 'Golduck', 'GOLDUCK', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (56, 'Mankey', 'MANKEY', 'Lutador', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (57, 'Primeape', 'PRIMEAPE', 'Lutador', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (58, 'Growlithe', 'GROWLITHE', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (59, 'Arcanine', 'ARCANINE', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (60, 'Poliwag', 'POLIWAG', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (61, 'Poliwhirl', 'POLIWHIRL', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (62, 'Poliwrath', 'POLIWRATH', 'Água', 'Lutador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (63, 'Abra', 'ABRA', 'Psíquico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (64, 'Kadabra', 'KADABRA', 'Psíquico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (65, 'Alakazam', 'ALAKAZAM', 'Psíquico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (66, 'Machop', 'MACHOP', 'Lutador', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (67, 'Machoke', 'MACHOKE', 'Lutador', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (68, 'Machamp', 'MACHAMP', 'Lutador', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (69, 'Bellsprout', 'BELLSPROUT', 'Grama', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (70, 'Weepinbell', 'WEEPINBELL', 'Grama', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (71, 'Victreebel', 'VICTREEBELL', 'Grama', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (72, 'Tentacool', 'TENTACOOL', 'Água', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (73, 'Tentacruel', 'TENTACRUEL', 'Água', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (74, 'Geodude', 'GEODUDE', 'Pedra', 'Terra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (75, 'Graveler', 'GRAVELER', 'Pedra', 'Terra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (76, 'Golem', 'GOLEM', 'Pedra', 'Terra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (77, 'Ponyta', 'PONYTA', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (78, 'Rapidash', 'RAPIDASH', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (79, 'Slowpoke', 'SLOWPOKE', 'Água', 'Psíquico');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (80, 'Slowbro', 'SLOWBRO', 'Água', 'Psíquico');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (81, 'Magnemite', 'MAGNEMITE', 'Elétrico', 'Metal');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (82, 'Magneton', 'MAGNETON', 'Elétrico', 'Metal');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (83, 'Farfetchd', 'FARFETCHD', 'Normal', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (84, 'Doduo', 'DODUO', 'Normal', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (85, 'Dodrio', 'DODRIO', 'Normal', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (86, 'Seel', 'SEEL', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (87, 'Dewgong', 'DEWGONG', 'Água', 'Gelo');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (88, 'Grimer', 'GRIMER', 'Venenoso', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (89, 'Muk', 'MUK', 'Venenoso', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (90, 'Shellder', 'SHELLDER', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (91, 'Cloyster', 'CLOYSTER', 'Água', 'Gelo');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (92, 'Gastly', 'GASTLY', 'Fantasma', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (93, 'Haunter', 'HAUNTER', 'Fantasma', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (94, 'Gengar', 'GENGAR', 'Fantasma', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (95, 'Onix', 'ONIX', 'Pedra', 'Terra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (96, 'Drowzee', 'DROWZEE', 'Psíquico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (97, 'Hypno', 'HYPNO', 'Psíquico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (98, 'Krabby', 'KRABBY', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (99, 'Kingler', 'KINGLER', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (100, 'Voltorb', 'VOLTORB', 'Elétrico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (101, 'Electrode', 'ELECTRODE', 'Elétrico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (102, 'Exeggcute', 'EXEGGCUTE', 'Grama', 'Psíquico');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (103, 'Exeggutor', 'EXEGGUTOR', 'Grama', 'Psíquico');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (104, 'Cubone', 'CUBONE', 'Terra', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (105, 'Marowak', 'MAROWAK', 'Terra', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (106, 'Hitmonlee', 'HITMONLEE', 'Lutador', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (107, 'Hitmonchan', 'HITMONCHAN', 'Lutador', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (108, 'Lickitung', 'LICKITUNG', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (109, 'Koffing', 'KOFFING', 'Venenoso', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (110, 'Weezing', 'WEEZING', 'Venenoso', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (111, 'Rhyhorn', 'RHYHORN', 'Terra', 'Pedra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (112, 'Rhydon', 'RHYDON', 'Terra', 'Pedra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (113, 'Chansey', 'CHANSEY', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (114, 'Tangela', 'TANGELA', 'Grama', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (115, 'Kangaskhan', 'KANGASKHAN', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (116, 'Horsea', 'HORSEA', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (117, 'Seadra', 'SEADRA', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (118, 'Goldeen', 'GOLDEEN', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (119, 'Seaking', 'SEAKING', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (120, 'Staryu', 'STARYU', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (121, 'Starmie', 'STARMIE', 'Água', 'Psíquico');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (122, 'Mr. Mime', 'MRMIME', 'Psíquico', 'Fada');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (123, 'Scyther', 'SCYTHER', 'Inseto', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (124, 'Jynx', 'JYNX', 'Gelo', 'Psíquico');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (125, 'Electabuzz', 'ELECTABUZZ', 'Elétrico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (126, 'Magmar', 'MAGMAR', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (127, 'Pinsir', 'PINSIR', 'Inseto', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (128, 'Tauros', 'TAUROS', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (129, 'Magikarp', 'MAGIKARP', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (130, 'Gyarados', 'GYARADOS', 'Água', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (131, 'Lapras', 'LAPRAS', 'Água', 'Gelo');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (132, 'Ditto', 'DITTO', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (133, 'Eevee', 'EEVEE', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (134, 'Vaporeon', 'VAPOREON', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (135, 'Jolteon', 'JOLTEON', 'Elétrico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (136, 'Flareon', 'FLAREON', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (137, 'Porygon', 'PORYGON', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (138, 'Omanyte', 'OMANYTE', 'Pedra', 'Água');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (139, 'Omastar', 'OMASTAR', 'Pedra', 'Água');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (140, 'Kabuto', 'KABUTO', 'Pedra', 'Água');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (141, 'Kabutops', 'KABUTOPS', 'Pedra', 'Água');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (142, 'Aerodactyl', 'AERODACTYL', 'Pedra', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (143, 'Snorlax', 'SNORLAX', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (144, 'Articuno', 'ARTICUNO', 'Gelo', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (145, 'Zapdos', 'ZAPDOS', 'Elétrico', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (146, 'Moltres', 'MOLTRES', 'Fogo', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (147, 'Dratini', 'DRATINI', 'Dragão', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (148, 'Dragonair', 'DRAGONAIR', 'Dragão', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (149, 'Dragonite', 'DRAGONITE', 'Dragão', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (150, 'Mewtwo', 'MEWTWO', 'Psíquico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (151, 'Mew', 'MEW', 'Psíquico', null);

//Lista de Pokémon da segunda geração

INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (152, 'Chikorita', 'CHIKORITA', 'Grama', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (153, 'Bayleef', 'BAYLEEF', 'Grama', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (154, 'Meganium', 'MEGANIUM', 'Grama', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (155, 'Cyndaquil', 'CYNDAQUIL', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (156, 'Quilava', 'QUILAVA', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (157, 'Typhlosion', 'TYPHLOSION', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (158, 'Totodile', 'TOTODILE', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (159, 'Croconaw', 'CROCONAW', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (160, 'Feraligatr', 'FERALIGATR', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (161, 'Sentret', 'SENTRET', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (162, 'Furret', 'FURRET', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (163, 'Hoothoot', 'HOOTHOOT', 'Normal', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (164, 'Noctowl', 'NOCTOWL', 'Normal', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (165, 'Ledyba', 'LEDYBA', 'Inseto', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (166, 'Ledian', 'LEDIAN', 'Inseto', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (167, 'Spinarak', 'SPINARAK', 'Inseto', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (168, 'Ariados', 'ARIADOS', 'Inseto', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (169, 'Crobat', 'CROBAT', 'Venenoso', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (170, 'Chinchou', 'CHINCHOU', 'Água', 'Elétrico');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (171, 'Lanturn', 'LANTURN', 'Água', 'Elétrico');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (172, 'Pichu', 'PICHU', 'Elétrico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (173, 'Cleffa', 'CLEFFA', 'Fada', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (174, 'Igglybuff', 'IGGLYBUFF', 'Normal', 'Fada');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (175, 'Togepi', 'TOGEPI', 'Fada', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (176, 'Togetic', 'TOGETIC', 'Fada', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (177, 'Natu', 'NATU', 'Psíquico', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (178, 'Xatu', 'XATU', 'Psíquico', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (179, 'Mareep', 'MAREEP', 'Elétrico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (180, 'Flaaffy', 'FLAAFFY', 'Elétrico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (181, 'Ampharos', 'AMPHAROS', 'Elétrico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (182, 'Bellossom', 'BELLOSSOM', 'Grama', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (183, 'Marill', 'MARILL', 'Água', 'Fada');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (184, 'Azumarill', 'AZUMARILL', 'Água', 'Fada');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (185, 'Sudowoodo', 'SUDOWOODO', 'Pedra', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (186, 'Politoed', 'POLITOED', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (187, 'Hoppip', 'HOPPIP', 'Grama', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (188, 'Skiploom', 'SKIPLOOM', 'Grama', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (189, 'Jumpluff', 'JUMPLUFF', 'Grama', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (190, 'Aipom', 'AIPOM', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (191, 'Sunkern', 'SUNKERN', 'Grama', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (192, 'Sunflora', 'SUNFLORA', 'Grama', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (193, 'Yanma', 'YANMA', 'Inseto', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (194, 'Wooper', 'WOOPER', 'Água', 'Terra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (195, 'Quagsire', 'QUAGSIRE', 'Água', 'Terra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (196, 'Espeon', 'ESPEON', 'Psíquico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (197, 'Umbreon', 'UMBREON', 'Sombra', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (198, 'Murkrow', 'MURKROW', 'Sombra', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (199, 'Slowking', 'SLOWKING', 'Água', 'Psíquico');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (200, 'Misdreavus', 'MISDREAVUS', 'Fantasma', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (201, 'Unown', 'UNOWN', 'Psíquico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (202, 'Wobbuffet', 'WOBBUFFET', 'Psíquico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (203, 'Girafarig', 'GIRAFARIG', 'Normal', 'Psíquico');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (204, 'Pineco', 'PINECO', 'Inseto', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (205, 'Forretress', 'FORRETRESS', 'Inseto', 'Metal');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (206, 'Dunsparce', 'DUNSPARCE', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (207, 'Gligar', 'GLIGAR', 'Terra', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (208, 'Steelix', 'STEELIX', 'Metal', 'Terra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (209, 'Snubbull', 'SNUBBULL', 'Fada', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (210, 'Granbull', 'GRANBULL', 'Fada', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (211, 'Qwilfish', 'QWILFISH', 'Água', 'Venenoso');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (212, 'Scizor', 'SCIZOR', 'Inseto', 'Metal');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (213, 'Shuckle', 'SHUCKLE', 'Inseto', 'Pedra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (214, 'Heracross', 'HERACROSS', 'Inseto', 'Lutador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (215, 'Sneasel', 'SNEASEL', 'Sombra', 'Gelo');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (216, 'Teddiursa', 'TEDDIURSA', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (217, 'Ursaring', 'URSARING', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (218, 'Slugma', 'SLUGMA', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (219, 'Magcargo', 'MAGCARGO', 'Fogo', 'Pedra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (220, 'Swinub', 'SWINUB', 'Gelo', 'Terra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (221, 'Piloswine', 'PILOSWINE', 'Gelo', 'Terra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (222, 'Corsola', 'CORSOLA', 'Água', 'Pedra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (223, 'Remoraid', 'REMORAID', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (224, 'Octillery', 'OCTILLERY', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (225, 'Delibird', 'DELIBIRD', 'Gelo', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (226, 'Mantine', 'MANTINE', 'Água', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (227, 'Skarmory', 'SKARMORY', 'Metal', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (228, 'Houndour', 'HOUNDOUR', 'Sombra', 'Fogo');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (229, 'Houndoom', 'HOUNDOOM', 'Sombra', 'Fogo');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (230, 'Kingdra', 'KINGDRA', 'Água', 'Dragão');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (231, 'Phanpy', 'PHANPY', 'Terra', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (232, 'Donphan', 'DONPHAN', 'Terra', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (233, 'Porygon2', 'PORYGON2', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (234, 'Stantler', 'STANTLER', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (235, 'Smeargle', 'SMEARGLE', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (236, 'Tyrogue', 'TYROGUE', 'Lutador', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (237, 'Hitmontop', 'HITMONTOP', 'Lutador', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (238, 'Smoochum', 'SMOOCHUM', 'Gelo', 'Psíquico');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (239, 'Elekid', 'ELEKID', 'Elétrico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (240, 'Magby', 'MAGBY', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (241, 'Miltank', 'MILTANK', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (242, 'Blissey', 'BLISSEY', 'Normal', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (243, 'Raikou', 'RAIKOU', 'Elétrico', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (244, 'Entei', 'ENTEI', 'Fogo', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (245, 'Suicune', 'SUICUNE', 'Água', null);
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (246, 'Larvitar', 'LARVITAR', 'Pedra', 'Terra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (247, 'Pupitar', 'PUPITAR', 'Pedra', 'Terra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (248, 'Tyranitar', 'TYRANITAR', 'Pedra', 'Sombra');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (249, 'Lugia', 'LUGIA', 'Psíquico', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (250, 'Ho-Oh', 'HOOH', 'Fogo', 'Voador');
INSERT INTO pokemon (numero, nome, descricao, tipo1, tipo2) VALUES (251, 'Celebi', 'CELEBI', 'Psíquico', 'Grama');